package entities;
// Generated 27-feb-2018 17:40:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History  implements java.io.Serializable {


     private Integer id;
     private Sudoku sudoku;
     private User user;
     private Date time;

    public History() {
    }

    public History(Sudoku sudoku, User user, Date time) {
       this.sudoku = sudoku;
       this.user = user;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sudoku getSudoku() {
        return this.sudoku;
    }
    
    public void setSudoku(Sudoku sudoku) {
        this.sudoku = sudoku;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


