package entities;
// Generated 02-mar-2018 22:25:03 by Hibernate Tools 4.3.1



/**
 * History generated by hbm2java
 */
public class History  implements java.io.Serializable {


     private Integer id;
     private Sudoku sudoku;
     private User user;
     private int time;

    public History() {
    }

    public History(Sudoku sudoku, User user, int time) {
       this.sudoku = sudoku;
       this.user = user;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sudoku getSudoku() {
        return this.sudoku;
    }
    
    public void setSudoku(Sudoku sudoku) {
        this.sudoku = sudoku;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getTime() {
        return this.time;
    }
    
    public void setTime(int time) {
        this.time = time;
    }




}


