package entities;
// Generated 27-feb-2018 17:40:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sudoku generated by hbm2java
 */
public class Sudoku  implements java.io.Serializable {


     private Integer id;
     private int description;
     private String level;
     private String unsolved;
     private String solved;
     private Set histories = new HashSet(0);

    public Sudoku() {
    }

	
    public Sudoku(int description, String level, String unsolved, String solved) {
        this.description = description;
        this.level = level;
        this.unsolved = unsolved;
        this.solved = solved;
    }
    public Sudoku(int description, String level, String unsolved, String solved, Set histories) {
       this.description = description;
       this.level = level;
       this.unsolved = unsolved;
       this.solved = solved;
       this.histories = histories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDescription() {
        return this.description;
    }
    
    public void setDescription(int description) {
        this.description = description;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getUnsolved() {
        return this.unsolved;
    }
    
    public void setUnsolved(String unsolved) {
        this.unsolved = unsolved;
    }
    public String getSolved() {
        return this.solved;
    }
    
    public void setSolved(String solved) {
        this.solved = solved;
    }
    public Set getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set histories) {
        this.histories = histories;
    }




}


