package entities;
// Generated 02-mar-2018 9:26:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sudoku generated by hbm2java
 */
public class Sudoku  implements java.io.Serializable {


     private Integer id;
     private String description;
     private int level;
     private String unsolved;
     private String solved;
     private Set histories = new HashSet(0);

    public Sudoku() {
    }

	
    public Sudoku(String description, int level, String unsolved, String solved) {
        this.description = description;
        this.level = level;
        this.unsolved = unsolved;
        this.solved = solved;
    }
    public Sudoku(String description, int level, String unsolved, String solved, Set histories) {
       this.description = description;
       this.level = level;
       this.unsolved = unsolved;
       this.solved = solved;
       this.histories = histories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public String getUnsolved() {
        return this.unsolved;
    }
    
    public void setUnsolved(String unsolved) {
        this.unsolved = unsolved;
    }
    public String getSolved() {
        return this.solved;
    }
    
    public void setSolved(String solved) {
        this.solved = solved;
    }
    public Set getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set histories) {
        this.histories = histories;
    }

    @Override
    public String toString() {
        return "Sudoku{ \n" + 
                "id=" + id + "\n"+
                " description=" + description + "\n"+
                " level=" + level + "\n"+
                " unsolved=" + unsolved + "\n"+
                " solved=" + solved + "\n"+
                " histories=" + histories + "\n"+
                '}';
    }

 


}


